apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: retail-store-pod-monitor
  namespace: staging
  labels:
    prometheus: prometheus-kube-prometheus-prometheus
spec:
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      app: my-retail-store
