apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: tea-store-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: tea-store
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tea-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /store
            pathType: Exact
            backend:
              serviceName: tea-store-service
              servicePort: 80
