apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: tea-store-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: tea-store
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ts-ingress
#   namespace: staging
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
# spec:
#   ingressClassName: alb
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Exact
#             backend:
#               service:
#                 name: tea-store-service
#                 port: 
#                   name: http
