apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: retail-store-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: my-retail-store
