apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: tea-store-service
  labels:
    app: tea-store
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: tea-store
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tea-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /store
            backend:
              serviceName: tea-store-service
              servicePort: 80
