apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-website
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: my-website
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type:
        averageUtilization: 50
