apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
  namespace: staging
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: website-service
                port: 
                  name: http
--
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: controller-metrics-monitor
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
